title: Introduction to Molecular Dynamics Simulations with GROMACS
description: >-
  A tutorial on the introduction of molecular dynamics simulations with GROMACS
baseurl: "/tutorial_14_oct_25.github.io"
domain: "tutorial_14_oct_25_introduction.github.io" 
url: "https://risvicky.github.io"

remote_theme: sighingnow/jekyll-gitbook

# Build settings
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-remote-theme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
