title: Introduction to Molecular Dynamics Simulations with GROMACS
description: >-
  A tutorial on the introduction of molecular dynamics simulations with GROMACS
baseurl: "/tutorial_14_oct_25.github.io"
domain: "tutorial_14_oct_25_introduction.github.io" 
url: "https://risvicky.github.io"

remote_theme: sighingnow/jekyll-gitbook

# Build settings
plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-remote-theme

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock

#- jekyll-remote-theme # add this line to the plugins list if you already have one


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
